org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
neo_version_range=[21.1.235,21.1.249)
loader_version_range=[4,)

mod_id=wheel_grip_tuner
mod_name=Aeronautics Wheel Grip Tuner
mod_version=0.1.0
mod_group_id=dev.danzy189.wheelgriptuner
mod_license=MIT
